# frozen_string_literal: true

require "rake/clean"

file "JIS0208.TXT" do
  sh "curl -O ftp://ftp.unicode.org/Public/MAPPINGS/OBSOLETE/EASTASIA/JIS/JIS0208.TXT"
end

task default: "JIS0208.TXT"

CLOBBER.include("JIS0208.TXT")
