# frozen_string_literal: true

require "rake/clean"

file "JIS0208.TXT" do
  sh "curl -O ftp://ftp.unicode.org/Public/MAPPINGS/OBSOLETE/EASTASIA/JIS/JIS0208.TXT"
end

desc "Run unit test"
task :check => "jis0208_test.rb" do |t|
  sh "ruby #{t.source}"
end

task default: :check

CLOBBER.include("JIS0208.TXT")
